"""Updated res relationships

Revision ID: 3374f560d686
Revises: 284d64f7e2c3
Create Date: 2024-07-19 19:38:25.493847

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "3374f560d686"
down_revision = "284d64f7e2c3"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "restaurants",
        "order",
        existing_type=sa.VARCHAR(length=1000),
        nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "restaurants",
        "order",
        existing_type=sa.VARCHAR(length=1000),
        nullable=False,
    )
    # ### end Alembic commands ###
