"""Updated res relationships

Revision ID: 0f24f4065a2a
Revises: 3ad86fa36dbc
Create Date: 2024-07-19 19:25:59.995085

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "0f24f4065a2a"
down_revision = "3ad86fa36dbc"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "restaurants",
        sa.Column("group_restaurant_id", sa.Integer(), nullable=False),
    )
    op.create_foreign_key(
        None,
        "restaurants",
        "group_restaurants",
        ["group_restaurant_id"],
        ["id"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "restaurants", type_="foreignkey")
    op.drop_column("restaurants", "group_restaurant_id")
    # ### end Alembic commands ###
