"""Seed restaurants from TSV

Revision ID: 3ad86fa36dbc
Revises: 1eeb48f077f3
Create Date: 2024-07-19 18:23:58.786283

"""
from alembic import op

# revision identifiers, used by Alembic.
revision = "3ad86fa36dbc"
down_revision = "1eeb48f077f3"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(
        None,
        "group_restaurant_ratings",
        "group_restaurants",
        ["group_restaurant_id"],
        ["id"],
    )
    op.create_foreign_key(
        None,
        "group_restaurants",
        "restaurants",
        ["restaurant_id"],
        ["id"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "group_restaurants", type_="foreignkey")
    op.drop_constraint(None, "group_restaurant_ratings", type_="foreignkey")
    # ### end Alembic commands ###
