"""Updated res relationships

Revision ID: 1e5b1443ab6e
Revises: 0f24f4065a2a
Create Date: 2024-07-19 19:29:43.272122

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "1e5b1443ab6e"
down_revision = "0f24f4065a2a"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "restaurants_group_restaurant_id_fkey",
        "restaurants",
        type_="foreignkey",
    )
    op.drop_column("restaurants", "group_restaurant_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "restaurants",
        sa.Column(
            "group_restaurant_id",
            sa.INTEGER(),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.create_foreign_key(
        "restaurants_group_restaurant_id_fkey",
        "restaurants",
        "group_restaurants",
        ["group_restaurant_id"],
        ["id"],
    )
    # ### end Alembic commands ###
