"""Updated res relationships

Revision ID: 63c2e8a3f78a
Revises: 3374f560d686
Create Date: 2024-07-19 19:46:36.835661

"""

# revision identifiers, used by Alembic.
revision = "63c2e8a3f78a"
down_revision = "3374f560d686"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
